import { Response } from 'express';
import asyncHandler from 'express-async-handler';
import axios from 'axios';
import ContentHistory from '../models/ContentHistory.js';
import User from '../models/User.js';
import { AuthenticatedRequest } from '../types/index.js';

interface GenerateContentBody {
    prompt: string;
}

interface GeminiResponse {
    candidates: Array<{
        content: {
            parts: Array<{
                text: string;
            }>;
        };
    }>;
}

// Google AI Controller
export const googleAIController = asyncHandler(
    async (req: AuthenticatedRequest & { body: GenerateContentBody }, res: Response): Promise<void> => {
        const { prompt } = req.body;
        console.log("Prompt received:", prompt);

        // Validation
        if (!prompt) {
             res.status(400);
             throw new Error('Prompt is required');
        }

        try {
            // Using the latest Gemini 3 Pro Preview model
            // If you want faster/cheaper results, change 'gemini-3-pro-preview' to 'gemini-3-flash-preview'
            const modelId = 'gemini-3-pro-preview'; 
            
            const response = await axios.post<GeminiResponse>(
                `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${process.env.GEMINI_API_KEY}`,
                {
                    contents: [
                        {
                            parts: [
                                {
                                    text: prompt,
                                },
                            ],
                        },
                    ],
                    generationConfig: {
                        temperature: 0.9, // Higher for more creative/reasoning responses
                        topK: 40,
                        topP: 0.95,
                        maxOutputTokens: 8192, // Gemini 3 supports larger outputs, increased from 2000
                    },
                },
                {
                    headers: {
                        'Content-Type': 'application/json',
                    },
                }
            );

            const content = response.data?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

            if (!content) {
                throw new Error('No content generated by Gemini');
            }

            // Save to Content History
            const newContent = await ContentHistory.create({
                user: req.user?._id,
                content,
            });

            // Update User Stats
            const userFound = await User.findById(req.user?._id);
            if (userFound) {
                userFound.contentHistory.push(newContent._id);
                userFound.apiRequestCount += 1;
                await userFound.save();
            }

            res.status(200).json(content);

        } catch (error: any) {
            console.error('Error generating content:', error?.response?.data || error.message);

            if (axios.isAxiosError(error)) {
                if (error.response?.status === 401) {
                    res.status(401);
                    throw new Error('Invalid Gemini API key. Please check your configuration.');
                } else if (error.response?.status === 429) {
                    res.status(429);
                    throw new Error('API rate limit exceeded. Please try again later.');
                } else if (error.response?.status === 503) {
                    res.status(503);
                    throw new Error('Gemini service is temporarily overloaded. Please try again.');
                }
            }
            
            // Fallback error
            res.status(500);
            throw new Error(
                error.response?.data?.error?.message || error.message || 'Failed to generate content'
            );
        }
    }
);